<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>dstfarm</AssemblyName>
    <RootNamespace>DstFarm.Cli</RootNamespace>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
    <ProjectReference Include="..\DstFarm.Core\DstFarm.Core.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <Target Name="RemoveSeparatePublishSymbols" AfterTargets="Publish" Condition="'$(PublishSingleFile)' == 'true'">
    <ItemGroup>
      <SeparatePublishSymbols Include="$(PublishDir)*.pdb" />
    </ItemGroup>
    <Delete Files="@(SeparatePublishSymbols)" />
  </Target>

</Project>
